server/appserver/urls.py
from django.conf.urls import url
from appserver import views as app_view
from rest_framework_jwt.views import obtain_jwt_token
# from django.contrib.auth import views as auth_views
# from django.views.generic import RedirectView

urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^$', app_view.Login_view, name='login'),
    url(r'^home/$', app_view.home, name='home'),
    url(r'^logout/$', app_view.Wlogout, name='logout'),

    # url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    # url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    # url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^user/$', app_view.UserList.as_view(), name='user-list'),
    url(r'^user/(?P<pk>[0-9]+)/$', app_view.UserDetail.as_view()),
    url(r'^mlogout/', app_view.MLogout.as_view()),
    url(r'^profile-edit/$', app_view.ProfileEdit, name='editProfile'),
    url(r'^profile/$', app_view.Profile, name='Profile'),
    url(r'^list-docs/$', app_view.ListOutDocument, name='listDocument'),
    url(r'^basic-upload/$', app_view.BasicUploadView.as_view(), name='basic_upload'),
    url(r'^getall/$', app_view.getall, name='dashboard'),
    url(r'^edit/(?P<id>[0-9]+)/$', app_view.edit),
    url(r'^update/(?P<id>[0-9]+)/$', app_view.update),
    url(r'^delete/(?P<id>[0-9]+)/$', app_view.destroy),
    url(r'^upload/$', app_view.upload, name='uploading'),

    url(r'^download/$', app_view.download, name="download_mod"),

]

server/baseproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('appserver.urls', namespace='appserver')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.TEMP_UPLOAD_URL, document_root=settings.TEMP_UPLOAD_DIR_ROOT)


# # This is only needed when using runserver.
# if settings.DEBUG:
#     urlpatterns = patterns('',
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
#             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
#         ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

server/appserver/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Document(models.Model):
    name = models.CharField(max_length=1000, blank=True)
    title = models.CharField(max_length=1000, blank=True)
    abstract = models.CharField(max_length=10000, blank=True)
    file_path = models.CharField(max_length=1000, blank=True)
    obtain_topic = models.IntegerField(default=2)
    expect_topic = models.IntegerField(default=2)
    is_edit = models.BooleanField(default=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(null=True, blank=True)


class OverallScore(models.Model):
    document = models.ForeignKey(Document, related_name='upload_document')
    grammer_language = models.IntegerField(default=2)
    no_of_words = models.IntegerField(default=2)
    journal_title = models.IntegerField(default=2)
    author_nationality = models.IntegerField(default=2)
    article_type = models.IntegerField(default=2)
    score = models.CharField(max_length=1000, default="Intermidiate")
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('auth.Group', related_name='scoregroup')

server/appserver/forms.py
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.forms import AuthenticationForm
from django import forms

from appserver.models import Document, OverallScore


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
        print("inside login form", username)

        password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}))

        #self.fields['username'].widget.attrs['placeholder'] = u'Email'
        #self.fields['password'].widget.attrs['placeholder'] = u'Password'

        # self.helper = FormHelper()
        # self.helper.layout = Layout(
        #     Div(
        #         'username', css_class='input-wrapper'
        #     ),
        #     Div(
        #         'password', css_class='input-wrapper'
        #     ),
        #     ButtonHolder(
        #         Submit('login', 'Login', css_class='btn-primary')
        #     )
        # )

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                return self.cleaned_data
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class LoginNewForm(forms.Form):
    user = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-group form-control'}))
    password = forms.CharField(widget=forms.PasswordInput())


class DashboardForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'false'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'required': 'false'}))
    file = forms.FileField()


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('name', 'title', 'abstract', 'obtain_topic', 'expect_topic',)


class OverallScoreForm(forms.ModelForm):
    class Meta:
        model = OverallScore
        fields = "__all__"

server/appserver/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from zipfile import ZipFile
from django.conf import settings
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from appserver.serializers import UserSerializer, DocumentSerializer, OverallScoreSerializer
from appserver.forms import LoginForm, LoginNewForm, DashboardForm, DocumentForm
from appserver.models import Document, OverallScore
from django.views import generic
from django.views.generic import View
from django.contrib.auth import authenticate, logout, get_user_model, login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import JsonResponse
from datetime import datetime, timedelta
import pandas as pd
from django.utils import timezone
import shutil
import os
from main_engine import Getting_Score_Result

# from django.shortcuts import render_to_response, get_object_or_404
# from django.http import Http404, HttpResponse
# from django.template.loader import render_to_string
# from django.core.mail import send_mail
# from rest_framework.decorators import api_view
# from django.views.decorators.csrf import csrf_protect
# from django.template import RequestContext

# from language_assessment_acs.language_assessment_core import main_engine

# Global declaration of operation folder
ROOT_FOLDER = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#print("ROOT_FOLDER -->", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# sys.path.append("/home/shantakumar/Projects/git_lab_proj/language_assessment_acs/language_assessment_core/")
#
# sys.path.insert(0, ROOT_FOLDER)

# sys.path.append('../')
#

# Create your views here.
# import datetime


def Login_view(request):
    if request.method == 'POST':
        # POST, generate form with data from the request
        form = LoginNewForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        # uri = '/profile/user/'
        if user is not None and user.is_active:
            login(request, user)
            return redirect('appserver:dashboard')
            # return render(request, 'home.html', {"user" : user})
        else:
            form = LoginNewForm()
            return render(request, 'registration/login.html', {'form': form, 'errormessage': True})
    else:
        # GET, generate blank form
        form = LoginNewForm()
        return render(request, 'registration/login.html', {'form': form})


class LoginView(generic.FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'registration/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        print("user --->", user)
        uri = '/profile/user/'
        if user is not None and user.is_active:
            login(self.request, user)
            return render(self.request, 'home.html', {"user": user})

            if not user.is_staff:
                if self.request.GET.get('next') is not None and self.request.GET.get('next') != '':
                    uri = uri + '?next=' + self.request.GET.get('next')
                return redirect(uri)

            if self.request.GET.get('next') is not None and self.request.GET.get('next') != '':
                return redirect(self.request.GET.get('next'))

            return super(LoginView, self).form_valid(form)
        else:
            User = get_user_model()
            print(User._meta.fields)
            return self.form_invalid(form)


@login_required(login_url='appserver:login')
def home(request):
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        return render(request, 'home.html', {'user': user})
    else:
        return render(request, 'home.html', {})


def Wlogout(request):
    logout(request)
    return redirect('/')


# @api_view(['GET', 'POST', ])
def ListOutDocument(request, format=None):
    # print "inside predict web function", request.POST['title']
    if request.method == 'POST':
        form = DashboardForm(request.POST)

        if request.FILES:
            test_file_obj = request.FILES['testfile']
            # print("test file obj -->", test_file_obj )
            # resp = analysis_modeling(request, test_file_obj) # functon from doc analysis
            # resp = True

        else:
            resp = True

        return render(request, 'home.html', {"Result": resp})  # 'form':form


class BasicUploadView(View):
    def get(self, request):
        photos_list = Document.objects.all().order_by('-uploaded_at')
        print(photos_list)
        return render(self.request, 'uploadIndex.html', {'photos': photos_list})

    def post(self, request):
        form = DocumentForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.document.name, 'url': photo.document.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def get_request_user_group(request):
    request_user_groups = request.user.groups.all()
    if request_user_groups:
        request_user_group = request_user_groups[0]
    else:
        request_user_group = Group.objects.get(name='default')

    return request_user_group


@login_required(login_url='appserver:login')
def getall(request):
    request_user_group = get_request_user_group(request)
    print("get_request_user_group ---> ", request_user_group)
    score_data = OverallScore.objects.filter(created_by=request_user_group).order_by('-created_at')
    # score_data = OverallScore.objects.all().order_by('-created_at')
    score_list = []
    for sc in score_data:
        score_dict = {}
        score_dict['document'] = sc.document.name
        score_dict['document_id'] = sc.document.id
        score_dict['grammer_language'] = sc.grammer_language
        score_dict['no_of_words'] = sc.no_of_words
        score_dict['journal_title'] = sc.journal_title
        score_dict['author_nationality'] = sc.author_nationality
        score_dict['article_type'] = sc.article_type
        score_dict['overall_score'] = sc.score
        score_dict['topic'] = sc.document.expect_topic if sc.document.is_edit else sc.document.obtain_topic
        # datetime.datetime.strptime(sc.document.uploaded_at, "%Y/%m/%d") if sc.document.uploaded_at else ""
        score_dict['create_date'] = sc.document.uploaded_at.strftime("%d/%m/%Y") if sc.document.uploaded_at else " "
        # datetime.datetime.strptime(sc.document.modified_at, "%Y/%m/%d") if sc.document.modified_at else ""
        score_dict['modified_date'] = sc.document.modified_at.strftime("%d/%m/%Y") if sc.document.modified_at else " "
        score_list.append(score_dict)

    return render(request, 'getAll.html', {'scores': score_list})


@login_required(login_url='appserver:login')
def edit(request, id):
    document = Document.objects.get(id=id)
    return render(request, 'edit.html', {'document': document})


@login_required(login_url='appserver:login')
def upload(request, format=None):

    request_user_group = get_request_user_group(request)
    # print("upload_request_user_group ---> ", request_user_group.id)
    if request.method == 'POST':
        # form = DashboardForm(request.POST)
        if request.FILES:
            zip_file_obj = request.FILES['testfile']
            # print("test file obj -->", zip_file_obj)
            with ZipFile(zip_file_obj, 'r') as zip:
                # zip.printdir()
                zip_dir_list = zip.namelist()
                zip.extractall(settings.TEMP_UPLOAD_DIR_ROOT)
            zip.close()
            document_files = [x for x in zip_dir_list if x.endswith(('.doc', '.docx', '.DOC', '.DOCX'))]

            for doc in document_files:
                abs_doc_path = os.path.join(settings.TEMP_UPLOAD_DIR_ROOT, doc)
                doc_dir_path = os.path.join(settings.TEMP_UPLOAD_DIR_ROOT, doc.rsplit("/", 1)[0])
                result_df, file_topic_df = Getting_Score_Result(doc_dir_path, abs_doc_path)

                # topic_insert_cmd = "INSERT INTO appserver_document (uploaded_at, is_edit, abstract, expect_topic, name, obtain_topic, title, modified_at, file_path) VALUES (%s, '0', %s, %s, %s, %s, %s, NULL, %s);"
                # topic_insert_val = (datetime.datetime.now(tz=timezone.utc), str(file_topic_df['Abstract'][0]).encode('ascii', 'ignore').decode('ascii'), str(result_df['Topic'][0]),  str(
                #     file_topic_df['File Name'][0]), str(result_df['Topic'][0]), str(file_topic_df['Title'][0]).encode('ascii', 'ignore').decode('ascii'), path)
                # cursor.execute(topic_insert_cmd, topic_insert_val)
                #
                # score_insert_cmd = "INSERT INTO appserver_overallscore (grammer_language,no_of_words,journal_title,author_nationality,article_type,score,created_at,document_id) VALUES (%s,%s,%s,%s,%s,%s,%s,%s);"
                # score_insert_val = (str(result_df['Lang/Grammar'][0]), str(result_df['No of words'][0]), str(result_df['Journal code'][0]),
                #                     str(result_df['author nation'][0]), str(result_df['article type'][0]), result_df['Obtained Level'][0], datetime.datetime.now(), doc_id)

                doc_req_data = {"uploaded_at": datetime.now(), "is_edit": False, "abstract": str(

server/appserver/templates/base.html
<!-- templates/base.html -->
{% load static %}

<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

	<link rel="stylesheet" href="{% static 'assets/css/normalize.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/flag-icon.min.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}" type="text/css" />
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'assets/css/datepicker.css' %}"  type="text/css" />


  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
  <script src="{% static 'assets/js/vendor/jquery-3.3.1.js' %}"></script>
  <script src="{% static 'assets/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/loader.js' %}"></script>
  <script src="{% static 'assets/js/jsapi' %}"></script>


  {% block jqueryscript %}{% endblock %}

  <title>{% block title %} {% endblock %}</title>
</head>

<body class="{% block body_class %} {% endblock body_class %}">

    {% block content %}
    {% endblock %}

 

</body>
</html>

server/appserver/templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit{% endblock %}

{% block content %}

    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#"><img src="{% static 'images/ccs_logo_nav.png' %}">
                </a>
                <a class="navbar-brand hidden" href="#"><img src="{% static 'images/logo2.png' %}" alt="Logo">
                </a>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                       <!--  <a href= "#"> <i class="menu-icon fa fa-dashboard"></i>Check Stats </a> -->
                    </li>
                    <!-- /.menu-title -->
<!--                     <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>navbar</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-puzzle-piece"></i><a href="#">sample dropdown1</a>
                            </li>
                            <li><i class="fa fa-id-badge"></i><a href="#">sample dropdown2</a>
                            </li>
                            <li><i class="fa fa-bars"></i><a href="#">sample dropdown3</a>
                            </li>
                    </li> -->
                    </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa-bars"></i></a>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="{% static 'images/admin.jpg' %}" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="/profile/"><i class="fa fa- user"></i>My Profile</a>

<!--                             <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a> -->

                            <a class="nav-link" href="/logout"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                    <div class="language-select dropdown" id="language-select">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="language" aria-haspopup="true" aria-expanded="true">
                            <i class="flag-icon flag-icon-us"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language">
                            <div class="dropdown-item">
                                <span class="flag-icon flag-icon-fr"></span>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-es"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-us"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-it"></i>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </header>
        <!-- /header -->
        <!-- Header-->
        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Edit Document</h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3">
            <div class="animated fadeIn">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">

                                <div class="card-body card-block">                         

                                <form  enctype="multipart/form-data" method="post" class="form-horizontal" action="/update/{{document.id}}/" onsubmit="jQuery('#spinnerIcon').show();" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="col-lg-12">

                                        <div class="row form-group">
                                            <div class="col col-md-2">
                                                <label for="hf-text" class=" form-control-label"> <strong> Name </strong>
                                                </label>
                                            </div>
                                            <div class="col-12 col-md-9">
                                                    <input type="text" id="hf-text" name="name" class="form-control" required value="{{ document.name }}" disabled="True" /> 
                                            </div>
                                        </div>

                                        <div class="row form-group">
                                            <div class="col col-md-2">
                                                <label for="hf-text" class=" form-control-label"><strong> Title </strong>
                                                </label>
                                            </div>
                                            <div class="col-12 col-md-9">
                                                    <input type="text" id="hf-text" name="title" class="form-control" required value="{{ document.title }}" disabled="True" /> 

                                            </div>
                                        </div>
                                        <div class="row form-group">
                                            <div class="col col-md-2">
                                                <label for="hf-text" class=" form-control-label"><strong> Abstract </strong>
                                                </label>
                                            </div>
                                            <div class="col-12 col-md-9">
                                                    <textarea class="form-control" id="hf-genre" name="abstract" rows="12" disabled="True" > {{ document.abstract }}</textarea> <!-- required="required" -->
                                            </div>
                                        </div>

                                        <div class="row form-group">
                                            <div class="col col-md-2">
                                                <label for="hf-text" class=" form-control-label"><strong> Topic </strong>
                                                </label>
                                            </div>
                                            <div class="col-12 col-md-9">
                                                <input type="number" id="hf-text" name="topic" class="form-control" required value="{{ document.expect_topic }}" min="1"  max="3" /> 
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-12 text-center margn-15">
                                        
                                        <button type="submit" class="btn btn-primary btn-sm" style='margin-right:16px'>
                                             <i class="fa " id= "submit_btn" style="font-size:18px"></i> Submit
                                        </button>

                                        <button type="button" class="btn btn-primary btn-sm" onclick="window.history.go(-1); return false;"  style='margin-right:16px' >
                                             <i class="fa " id= "back_btn" style="font-size:18px"></i> Back
                                        </button>
                                        
                                        <a id="link-tag" href="/delete/{{document.id}}" onclick="return confirm('Are you sure you want to delete this?')" > Delete</a>

                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <!-- .animated -->
        </div>
        <!-- .content -->
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery("#spinnerIcon").hide();
  });

</script>

</div>

{% endblock %}



<!-- 

    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>  
        {% load staticfiles %}  
        <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    </head>  
    <body>  
    <form method="POST" class="post-form" action="/update/{{document.id}}/">  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  

      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Name:</label>  
        <div class="col-sm-4">  
            <input type="text" name="name" id="id_name" required maxlength="100" value="{{ document.name }}" />  
        </div>  
      </div>  

      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Title:</label>  
        <div class="col-sm-4">  
            <input type="text" name="title" id="id_title" required maxlength="100" value="{{ document.title }}" />  
        </div>  
      </div>  

      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Abstract:</label>  
        <div class="col-sm-4">  
            <textarea  rows="4" cols="50" name="abstract" id="id_abstract" required > {{ document.abstract }} </textarea>
        </div>  
      </div>  

        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Topic:</label>  
        <div class="col-sm-4">  
            <input type="text" name="topic" id="id_topic"  maxlength="254" value="{{ document.expect_topic }}" />  
        </div>  
      </div>  
 
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>  
        </div>  
    </form>  
    </body>  
    </html>   -->